name: example_dapp
description: Example for Wallet Connect SDK dapp implementation.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  barcode: ^2.2.3
  flutter_svg: ^1.1.6
  web3dart: ^2.3.0
  shared_preferences: ^2.0.7
  cupertino_icons: ^1.0.2
  eth_sig_util: ^0.0.3
  json_annotation: ^4.7.0
  bip39: ^1.0.6
  bip32: ^2.0.0
  wallet_connect:
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.0.0
  build_runner: ^2.0.0

flutter:
  uses-material-design: true
